allowBuilds:
    '@parcel/watcher': true
    '@prisma/engines': true
    '@swc/core': true
    esbuild: true
    prisma: true
    sharp: true
    unrs-resolver: true
ignoredBuiltDependencies:
    - sharp
    - unrs-resolver

minimumReleaseAge: 7200 # 5 days in minutes

strictDepBuilds: true

# trustPolicy: no-downgrade

savePrefix: ''

nodeLinker: isolated

preferWorkspacePackages: true

sharedWorkspaceLockfile: true
resolutionMode: highest

overrides:
    'semver@<7': 7.7.0
