allowBuilds:
    '@parcel/watcher': true
    '@swc/core': true
    esbuild: true
    sharp: true
    unrs-resolver: true
ignoredBuiltDependencies:
    - sharp
    - unrs-resolver

minimumReleaseAge: 10080 # 7 days in minutes

strictDepBuilds: true

trustPolicy: no-downgrade

savePrefix: ''

nodeLinker: isolated

preferWorkspacePackages: true

sharedWorkspaceLockfile: true

overrides:
    'semver@<7': 7.7.0
