/**
 * This file contains enums related to budgets in the application.
 * It defines the possible statuses and types of budgets that can be used.
 */
export enum BUDGET_STATUS {
	/**
	 * DRAFT status indicates that the budget is still being created or modified and is not yet finalized.
	 */
	DRAFT = 'draft',

	/**
	 * ACTIVE status indicates that the budget is currently in use and is being actively managed.
	 */
	ACTIVE = 'active',

	/**
	 * ARCHIVED status indicates that the budget is no longer active and has been archived for record-keeping purposes.
	 */
	ARCHIVED = 'archived',

	/**
	 * AI_GENERATED status indicates that the budget was generated by an AI system, possibly based on historical data or predictive analytics.
	 */
	AI_GENERATED = 'ai_generated',
}

/**
 * This enum defines the types of budgets that can be created in the application.
 */
export enum BUDGET_TYPE {
	/**
	 * PERSONAL type indicates that the budget is intended for individual use, allowing a single user to manage their finances.
	 */
	PERSONAL = 'personal',

	/**
	 * SHARED type indicates that the budget is intended for use by multiple users, allowing collaborative management of finances within a group or household.
	 */
	SHARED = 'shared',
}
